### ISSUE TITLE
您好，在抢购无人购买的票时仍然会失败，biliapi.py第225行的网址请求失败

### ISSUE THREAD

**Issue by hu-jiahuan** [kabaBZ/BiliTicket#2]
输入演出id(按回车结束):81174&from=pc_ticketlist
本演出共2场次
场次编号：1  场次名称：2024-04-04 周四  screen_id: 160526
场次编号：2  场次名称：2024-04-05 周五  screen_id: 160527
请选择场次编号：1
本场次共2票种
票种编号：1  票种名称：2024年纪念集章护照（非门票） - ￥8.8  票种SKUid：458181
票种编号：2  票种名称：单日早鸟票 - ￥70.0  票种SKUid：456706
票种编号：3  票种名称：单日预售票 - ￥85.0  票种SKUid：456660
票种编号：4  票种名称：单日快速预售票 - ￥110.0  票种SKUid：456673
票种编号：5  票种名称：单日黑卡预售票 - ￥238.0  票种SKUid：456758
请选择票种编号：1
修改buyer_info.json,保存后按回车
临时token: wGX-uBYAAT4OAAJ59AEAAQAHBW8.
error!!!:前方拥堵，请重试
False

"https://show.bilibili.com/api/ticket/order/createV2"请求失败

**Comment by kabaBZ** [comment]
id是纯数字，把后面去掉试试
